# Generated by Django 4.2.18 on 2025-05-21 11:52

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arpas_augmentedreality", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0, 0), dim=3, srid=0
            ),
        ),
    ]
